name: Build Natives
on:
  # Manual dispatch.
  workflow_dispatch:

jobs:
  #osx-x64:
  #osx-arm64:
  win-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: build zstd library
        run: ./scripts/zstd.py

      - uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: .artifacts/zstd/*.*
