name: Build Natives
on:
  # Manual dispatch.
  workflow_dispatch:

jobs:
  osx-x64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Deps
        run: brew install ninja

      - name: Build
        run: python ./scripts/osx.py

      - uses: actions/upload-artifact@v4
        with:
          name: osx-x64
          path: artifacts
          if-no-files-found: error

  linux-x64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Deps
        run: sudo apt install -y --no-install-recommends ninja-build libwayland-dev libxkbcommon-dev xorg-dev libgtk-4-dev

      - name: Build
        run: python ./scripts/linux.py

      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: artifacts
          if-no-files-found: error

  win-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Deps
        shell: cmd
        run: choco install ninja --limit-output --no-progress

      - name: Build
        shell: cmd
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
          python ./scripts/windows.py

      - uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: artifacts
          if-no-files-found: error
