name: Build Natives
on:
  # Manual dispatch.
  workflow_dispatch:

jobs:
  osx-x64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Deps
        run: brew install ninja

      - name: Build
        run: python ./scripts/osx.py

      - uses: actions/upload-artifact@v4
        with:
          name: osx-x64
          path: artifacts
          if-no-files-found: error

  linux-x64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: docker/build-push-action@v2
        with:
          tags: native-build:latest
          file: scripts/linux-build-env.Dockerfile
          push: false

      - uses: addnab/docker-run-action@v3
        with:
          image: native-build:latest
          run: python /work/scripts/linux.py
          options: -v ${{ github.workspace }}:/work

      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: artifacts
          if-no-files-found: error

  win-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Deps
        shell: cmd
        run: choco install ninja --limit-output --no-progress

      - name: Install VCPkg dependencies
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Build
        shell: cmd
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
          python ./scripts/windows.py

      - uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: artifacts
          if-no-files-found: error
